Resources:
  GoldenAMIPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: "Golden-AMI-Pipeline"
      RoleArn: "arn:aws:iam::216989130794:role/Code-pipeline-role"
      ArtifactStore:
        Type: "S3"
        Location: "demo-cicd-bucket-02"
      Stages:
        - Name: "Source"
          Actions:
            - Name: "GitHubSource"
              ActionTypeId:
                Category: "Source"
                Owner: "ThirdParty"
                Provider: "GitHub"
                Version: "1"
              Configuration:
                Owner: "ManojKumar23-cloud"
                Repo: "golden-ami-repo"
                Branch: "main"
                OAuthToken: "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"
              OutputArtifacts:
                - Name: "SourceOutput"
        - Name: "Build"
          Actions:
            - Name: "BuildAMI"
              ActionTypeId:
                Category: "Build"
                Owner: "AWS"
                Provider: "CodeBuild"
                Version: "1"
              Configuration:
                ProjectName: "GoldenAMI-Build"
              InputArtifacts:
                - Name: "SourceOutput"
              OutputArtifacts:
                - Name: "BuildOutput"
        - Name: "Deploy"
          Actions:
            - Name: "TriggerLambda"
              ActionTypeId:
                Category: "Invoke"
                Owner: "AWS"
                Provider: "Lambda"
                Version: "1"
              Configuration:
                FunctionName: "TriggerGoldenAMI"
